config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
require_relative '../../lib/util/DefaultAccount'
require_relative '../../lib/util/GenerateHMAC'

class StaticPagesController < ApplicationController
  def home
    @txn_req = ""
    @hmac = ""
    @keyID = ""

    txn_amt = params['txnAmt']
    if (!txn_amt.nil?)
      if (!txn_amt.empty?)
        a = Account.new
        @txn_req = generate_payload(txn_amt)
        @hmac = generate_signature(@txn_req, a.secret_key)
        @keyID = a.public_key

        puts "txnReq= " + @txn_req
        puts "hmac= " + @hmac
        puts "public_key= " + @keyID
      end
    end
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The eNETS integration test site.
  </small>
  <nav>
    <ul>
      <li><%= link_to "NETS",   'https://www.nets.com.sg/' %></li>
      <li><%= link_to "Developer-Page", 'https://api-developer.nets.com.sg/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "eNETS", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    home_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ENETSTest</title>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<script src="https://uat2.enets.sg/GW2/js/jquery-3.1.1.min.js"
    type="text/javascript"></script>
<script src="https://uat2.enets.sg/GW2/pluginpages/env.jsp"></script>
<script type="text/javascript"
    src="https://uat2.enets.sg/GW2/js/apps.js"></script>
<div class="center jumbotron">
  <h1>eNETS Test Portal</h1>

  <form class="input-form">
    <span class="a">Transaction Amount:   <input class="input" id="txnAmt" type="number" name="txnAmt" placeholder=""></span>
    <br><br>
    <input type="submit" value="Generate Payload">
    <br>
    <br>
    <div class="a">Transaction Request:</div> <%= text_area_tag(:txn_req, @txn_req, size: "100x6") %>
    <div class="a">HMAC:</div>  <%= text_area_tag(:hmac, @hmac, size: "100x1") %>
    <div class="a">Key ID:</div> <%= text_area_tag(:keyID, @keyID, size: "100x1") %>
    <br>
    <br>
    <input type="button" value="Send Payload" onclick="checkOut()" style="font-size : 15px;">
  </form>

</div>
<div class="payment-section">

  <fieldset>
      <div id="ajaxResponse"></div>
  </fieldset>
</div>
<script>
  function checkOut() {
  	// window.alert(txn_req.value);
    sendPayLoad(txn_req.value, hmac.value, keyID.value);
  };
</script>



<!-- <%= link_to image_tag("dev_at_nets.png", alt: "eNETS logo", height: "71", width:"202"),
            'https://api-developer.nets.com.sg/' %> -->